const Resources = {
    Images: {
        DEFAULT_AVATAR_URL: require("../assets/images/default_avatar.png").default,
        LOGO: require("../assets/images/logo.svg").default,
        LOGO_01: require("../assets/images/logo_01.png").default,
        LOGO_01_CIRCLE: require("../assets/images/logo_01_circle.png").default,
        SIDEBAR_BACKGROUND: require("../assets/images/Sidebar_Background.png").default,
        PATTERN:  require("../assets/images/Pattern.svg").default,
        PATTERN1:  require("../assets/images/Pattern1.svg").default,
        BG_SEARCH: require("../assets/images/bg_search.jpg").default,
        LEFT_FOOTER: require("../assets/images/Left_Footer.svg").default,
        RIGHT_FOOTER: require("../assets/images/Right_Footer.svg").default,
        INTRO: require("../assets/images/intro_1.png").default,
        INTRO_2: require("../assets/images/1 (7).jpg").default,
        NEW_GIF: require("../assets/images/news-gif.png").default,
        DEFAULT: require("../assets/images/default.jpg").default,
        REAL_ESTATE_LOGO: require("../assets/images/logoRealEstateWeb.png").default,
        COMMERCE_BANNER: require("../assets/images/commerceBanner.jpg").default,
        FLAG:{
            VN: require("../assets/images/flag/vietnam.png").default,
        },
        INTRO_IMG:{
            STRATEGY_SYSTEM_BG: require("../assets/images/intro/strategy_system_bg.jpg").default,
        },
        TEMP: {
            BANNER1: require("../assets/images/temp/commerce(1).jpg").default,
            BANNER2: require("../assets/images/temp/commerce(1).png").default,
            BANNER3: require("../assets/images/temp/commerce(2).jpg").default,
            BANNER4: require("../assets/images/temp/commerce(2).png").default,
            BANNER5: require("../assets/images/temp/commerce(3).jpg").default,
            BANNER6: require("../assets/images/temp/commerce(3).png").default,
        },
        
        PROMOTION_BANNER: require("../assets/images/promotion_banner.jpg").default,
        
    },
    Icon: {
        CUSTOMER: require("../assets/icons/CORE_VALUES/teamwork.svg").default,
        HAND_SHAKE: require("../assets/icons/CORE_VALUES/customer.svg").default,
        LOVE: require("../assets/icons/CORE_VALUES/trust.svg").default,
        QUANLITY: require("../assets/icons/CORE_VALUES/quality.svg").default,
        LIGHTBULD: require("../assets/icons/CORE_VALUES/innovation.svg").default,
        SALE: require("../assets/icons/for-sale.svg").default,
        MAIL: require("../assets/icons/mail.svg").default,
        RENT: require("../assets/icons/rent.svg").default,
        VERSION: require("../assets/icons/analysis.svg").default,
        MISSION: require("../assets/icons/goal.svg").default,
        SEARCH_YELLOW: require("../assets/icons/SearchYellow.svg").default,
        SEARCH_GREEN: require("../assets/icons/SearchGreen.svg").default,
        SMALL_SEARCH_GREEN: require("../assets/icons/small_search_green.svg").default,
        FIND_QUICK: require("../assets/icons/FindQuick.svg").default,
        SEARCH: require("../assets/icons/Search.svg").default,
        FILTER: require("../assets/icons/Filter.svg").default,
        RIGHT: require("../assets/icons/right.svg").default,
        BED: require("../assets/icons/bed.svg").default,
        ACREAGE: require("../assets/icons/acreage.svg").default,
        BATHTUB: require("../assets/icons/bathtub.svg").default,
        HEART: require("../assets/icons/heart.svg").default,
        HEART_ACTIVE: require("../assets/icons/heart_active.svg").default,
        HEART_WHITE: require("../assets/icons/heart-white.svg").default,
        HA: require("../assets/icons/ha.svg").default,
        HELP: require("../assets/icons/help.svg").default,
     
        SHIELD_ON: require("../assets/icons/shieldOn.svg").default,
        REFUND: require("../assets/icons/Refund.svg").default,
        FILE_TEXT: require("../assets/icons/fileText.svg").default,
        RESERVATION: require("../assets/icons/reservation.svg").default,
        CHEVRON_DOWN: require("../assets/icons/chevron_down.svg").default,
        CHEVRON_UP: require("../assets/icons/chevron_up.svg").default,
        POOL: require("../assets/icons/pool.svg").default,
        COFFEE_SHOP: require("../assets/icons/coffee_shop.svg").default,
        COFFEE_CUP: require("../assets/icons/coffee_cup.svg").default,
        WAITER: require("../assets/icons/waiter.svg").default,
        PARKING: require("../assets/icons/parking.svg").default,
        WINDOW: require("../assets/icons/window.svg").default,
        HOME: require("../assets/icons/home.svg").default,
        PIN: require("../assets/icons/pin.svg").default,
        DOWNLOAD: require("../assets/icons/download.svg").default,
        CHEVRON_LEFT: require("../assets/icons/chevron_left.svg").default,
        UPLOAD: require("../assets/icons/upload.svg").default,
        DEGREE_360: require("../assets/icons/360.svg").default,
        YOUTUBE_LINEAL: require("../assets/icons/youtube_lineal.svg").default,
        BATHROOM: require("../assets/icons/bathroom.svg").default,
        CACULATOR: require("../assets/icons/calculator.svg").default,
        UNSELECT: require("../assets/icons/unselect.svg").default,
        SELECTED: require("../assets/icons/selected.svg").default,
        UNSELECT_1: require("../assets/icons/unselect_1.svg").default,
        SELECTED_1: require("../assets/icons/selected_1.svg").default,
        CHECK_IN: require("../assets/icons/Checkin.svg").default,
        GLOBE: require("../assets/icons/Globe.svg").default,
        TWITTER: require("../assets/icons/twitter.svg").default,
        LINK_IN: require("../assets/icons/linkedin.svg").default,
        YOUTUBE: require("../assets/icons/youtube.svg").default,
        FB: require("../assets/icons/facebook.svg").default,
        BCT: require("../assets/icons/logoSaleNoti.png").default,
        SHOPPING_CART: require("../assets/icons/shopping_cart.svg").default,
        SHOPPING_CART_BLACK: require("../assets/icons/shopping_cart_black.svg").default,
        ZALO: require("../assets/icons/Zalo.svg").default,
        PHONE: require("../assets/icons/Phone.svg").default,
        CUSTOMER_SERVICE: require("../assets/icons/customer-service.svg").default,
        ARROW: require("../assets/icons/Arrow.svg").default,
        SHOPPING_CART_YELLOW: require("../assets/icons/ShoppingCart.svg").default,
        HEART_YELLOW: require("../assets/icons/HeartYellow.svg").default,
        CLOSE_YELLOW: require("../assets/icons/close_yellow.svg").default,
        CLOSE_HEADER: require("../assets/icons/close-header.svg").default,
        LOGO_FB: require("../assets/icons/logo_fb.svg").default,
        LOGO_GG: require("../assets/icons/logo_gg.svg").default,
        LOGO_MAIL: require("../assets/icons/logo_mail.svg").default,
        LOGO_TW: require("../assets/icons/logo_tw.svg").default,
        LOGO_G_PLUS: require("../assets/icons/logo_g_plus.svg").default,
        CIRCLE_CHECKED: require("../assets/icons/circle_checked.svg").default,
        EXIT: require("../assets/icons/exit.svg").default,
        CREDIT_CARD: require("../assets/icons/credit_card.svg").default,
        INTRO_ARROW_UP: require("../assets/icons/intro_arrow_up.svg").default,
        INTRO_ARROW_RIGHT: require("../assets/icons/intro_arrow_right.svg").default,
        ARROW_UP: require("../assets/icons/arrow_up.svg").default,
        DASH: require("../assets/icons/dash.svg").default,
        SUCCESS_CYCLE: require("../assets/icons/success_cycle.svg").default,
        ADD: require("../assets/icons/add.svg").default,
        MINUS: require("../assets/icons/minus.svg").default,
        MOBILE_CARD: require("../assets/icons/mobile_card.svg").default,
        CURRENCY_EXCHANGE: require("../assets/icons/currency_exchange.svg").default,
        COLLECTION_ENCASHMENT: require("../assets/icons/collection_encashment.svg").default,
        WHITE_TICK: require("../assets/icons/white_tick.svg").default,
        SUCCESS: require("../assets/icons/success.svg").default,
        WAITING_APPROVE: require("../assets/icons/waiting_approve.svg").default,
        VCB: require("../assets/icons/vcb.svg").default,
        TCB: require("../assets/icons/tcb.svg").default,
        ACB: require("../assets/icons/acb.svg").default,
        KNOT_LOGO: require("../assets/icons/knot_logo.svg").default,
        LEFT: require("../assets/icons/left.svg").default,
        MY_ORDER: require("../assets/icons/my_order.svg").default,
        PROFILE: require("../assets/icons/profile.svg").default,
        LOGO_PL_WHITE: require("../assets/icons/LOGO_PL_WHITE.svg").default,
        FLOWER: require("../assets/icons/flower.svg").default,
        DONG_GREEN: require("../assets/icons/Green/Dong.svg").default,
        GRID_GREEN: require("../assets/icons/Green/Grid.svg").default,
        HOME_GREEN: require("../assets/icons/Green/Home.svg").default,
        LEFT_GREEN: require("../assets/icons/Green/Left.svg").default,
        GREEN_SQUARE: require("../assets/icons/info/metering.svg").default,
        GREEN_BUILDUP_AREA: require("../assets/icons/info/blueprint.svg").default,
        GREEN_CARPET_AREA: require("../assets/icons/info/carpetArea.svg").default,
        GREEN_LONG: require("../assets/icons/info/long.svg").default,
        GREEN_WIDTH: require("../assets/icons/info/width.svg").default,
        GREEN_BED: require("../assets/icons/info/bed.svg").default,
        GREEN_BATH: require("../assets/icons/info/bathtub.svg").default,
        GREEN_ORIENTATION: require("../assets/icons/info/compass.svg").default,
        GREEN_APARTMENT: require("../assets/icons/green_apartment.svg").default,
        GREEN_MAP: require("../assets/icons/Green/Map.svg").default,
        GREEN_APARTMENT_SQUARE: require("../assets/icons/green_apartment_square.svg").default,
        GREEN_HOME_SCALE: require("../assets/icons/house_scale.svg").default,
        GREEN_VILLA: require("../assets/icons/Green/town.svg").default,
        GREEN_HOTEL: require("../assets/icons/Green/hotel.svg").default,
        GREEN_DEGREE: require("../assets/icons/green_degree.svg").default,
        SMALL_GREEN_BED: require("../assets/icons/small_green_bed.svg").default,
        IMAGE: require("../assets/icons/image.svg").default,
        DOC: require("../assets/icons/doc.svg").default,
        WHITE_SQUARE: require("../assets/icons/white_square.svg").default,
        WHITE_BATH: require("../assets/icons/white_bath.svg").default,
        WHITE_BED: require("../assets/icons/white_bed.svg").default,
        USER: require("../assets/icons/User.svg").default,
        PROJECT: require("../assets/icons/Project.svg").default,
        SPEAKER: require("../assets/icons/News.svg").default,
        CALL_GREEN: require("../assets/icons/Call_green.svg").default,
        CAL: require("../assets/icons/Cal.svg").default,
        CALENDER: require("../assets/icons/Calendar.svg").default,
        CASH: require("../assets/icons/Cash.svg").default,
        PERCENT: require("../assets/icons/Percent.svg").default,
        ACB_BORDER: require("../assets/icons/ACB_BORDER.svg").default,
        VCB_BORDER: require("../assets/icons/VCB_BORDER.svg").default,
        HD: require("../assets/icons/HD.svg").default,
        SCB: require("../assets/icons/SCB.svg").default,
        TCB_BORDER: require("../assets/icons/TCB_BORDER.svg").default,
        VISA: require("../assets/icons/VISA.svg").default,
        BANKING: require("../assets/icons/ITN_BANKING.svg").default,
        MASTER: require("../assets/icons/Master.svg").default,
        ERR_CYCLE: require("../assets/icons/ERR_CYCLE.svg").default,
        PRINTER: require("../assets/icons/Printer.svg").default,
        CALL: require("../assets/icons/call.svg").default,
        SEARCH_BLACK: require("../assets/icons/Search_Black.svg").default,
        GRAY_PREVIOUS: require("../assets/icons/gray_revious.svg").default,
        YELLOW_NEXT: require("../assets/icons/yellow_next.svg").default,
        GRAY_WINDOW: require("../assets/icons/gray_window.svg").default,
        GRAY_MARKET: require("../assets/icons/gray_market.svg").default,
        GRAY_TICKET: require("../assets/icons/gray_ticket.svg").default,
        GRAY_GIFT: require("../assets/icons/gray_gift.svg").default,
        GRAY_HOME: require("../assets/icons/gray_home.svg").default,
        ZOOM_IN: require("../assets/icons/ZoomIn.svg").default,
        MARKER: require("../assets/icons/marker.svg").default,
        LEAVES: require("../assets/icons/leaves.svg").default,
        YOUTUBE_PLAY:  require("../assets/icons/youtube (1).svg").default,
        STATUS:{
            OPENED_SALE: require("../assets/icons/status/key.svg").default,
            ON_SALE:  require("../assets/icons/status/for-sale.svg").default,
            SOLD:  require("../assets/icons/status/property.svg").default,
            HOT:  require("../assets/icons/status/hot.svg").default,
            HOT_1:  require("../assets/icons/status/promotional.svg").default,
        },
    },
    Video:{
        LOGO: require("../assets/video/Logo_Dragon.mp4").default,
        BANNER_1: require("../assets/video/BG_VIDEO.mp4").default,
    },
    Gif:{
        LOGO:  require("../assets/images/logo_2.gif").default,
    },
    FILE:{
        PDF: require("../assets/PLSL_WebsitePolicy_20Aug21.pdf").default,
        MP3: require("../assets/video/temp.mp3").default,
    }
};

export default Resources;
